apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coffee-app.backend.name" . }}
  labels:
    {{- include "coffee-app.backend.labels" . | nindent 4 }}
data:
    MONGODB_HOST: {{ .Values.backend.mongodb.host | quote }}
    MONGODB_PORT: {{ .Values.backend.mongodb.port | quote }}
    MONGODB_USERNAME: {{ .Values.backend.mongodb.username | quote }}