apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coffee-app.frontend.name" . }}
  labels:
    {{- include "coffee-app.frontend.labels" . | nindent 4 }}
data:
  env.js: |
    window.env = {
      BACKEND_URL: 'https://{{ .Values.backend.ingress.host }}',
      AUTH_URL: "https://{{ .Values.keycloak.ingress.hostname }}/realms/{{ .Values.keycloak.realm }}",
    };