apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coffee-app.frontend.name" . }}
data:
  env.js: |
    window.env = {
      BACKEND_URL: 'https://{{ .Values.backend.ingress.host }}',
    };