apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .Values.kafka.saslUserName }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    - host: '*'
      operations:
        - All
      resource:
        name: coffee-images
        patternType: literal
        type: topic
    - host: '*'
      operations:
        - All
      resource:
        type: cluster
      type: allow
    - host: '*'
      operations:
        - All
      resource:
        type: group
        name: {{ .Values.resizer.kafkaConsumerGroup}}
        patternType: literal
      type: allow