apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coffee-app.resizer.name" . }}
  labels:
    {{- include "coffee-app.resizer.labels" . | nindent 4 }}
data:
    LOG_LEVEL: {{ .Values.resizer.logLevel | quote }}
    THUMBNAIL_WIDTH: {{ .Values.resizer.thumbnailWidth | quote }}
    THUMBNAIL_FORMAT: {{ .Values.resizer.thumbnailFormat | quote }}
    KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.kafka.clusterName }}-kafka-brokers:9092"
    KAFKA_TOPIC: "coffee-images"
    KAFKA_CONSUMER_GROUP: {{ .Values.resizer.kafkaConsumerGroup | quote }}
    KAFKA_SSL_PROTOCOL: {{ .Values.resizer.kafkaSslProtocol | quote }}
    KAFKA_SSL_CAFILE: {{ .Values.resizer.kafkaSslCafile | quote }}
    KAFKA_SASL_MECHANISM: {{ .Values.resizer.kafkaSaslMechanism | quote }}
    kafka_sasl_username: {{ .Values.kafka.saslUserName | quote }}
    REDUCE_TYPE: {{ .Values.resizer.reduceType | quote }}
    MINIO_HOST: {{ .Values.backend.minio.host | quote }}
    MINIO_PORT: {{ .Values.backend.minio.port | quote }}
    MINIO_ORIGINAL_IMAGES_PREFIX: {{ .Values.resizer.original_images_prefix | quote }}
    MINIO_COFFEE_IMAGES_BUCKET: {{ .Values.resizer.offee_images_bucket | quote }}
